version: '3.7'

services:
  database:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=restapi
      - POSTGRES_PASSWORD=restapi
      - POSTGRES_DB=restapi_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rest-api:
    build: .
    command: gunicorn nerfapi.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.develop
    expose:
       - 8000
    depends_on:
      - database

  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    depends_on:
      - rest-api

volumes:
  postgres_data:

